# StormCast regression training using one month of SINGV data.

defaults:
  - dataset/singv_1month
  - model/stormcast
  - training/singv_regression_1month
  - sampler/edm_deterministic
  - hydra/default
  - _self_