# Run inference using the one-month SINGV regression and diffusion models.
#
# Training:
#   1995-01-01 through 1995-01-31
#
# Inference data:
#   1995-02-01 through 1995-02-07

defaults:
  - dataset/singv_1month
  - model/singv_diffusion_1month # change to singv_regression_1month to perform inference using only regression model
  - sampler/edm_deterministic
  - inference/singv_inference_1month
  - _self_

inference:
  regression_checkpoint: /scratch/users/nus/e1155933/retraining/runs/singv-regression-1month/training-1000steps/checkpoints_regression/StormCastUNet.0.1000.mdlus
  diffusion_checkpoint: /scratch/users/nus/e1155933/retraining/runs/singv-diffusion-1month/training-1000steps/checkpoints_diffusion/EDMPrecond.0.1000.mdlus

  # First input time in the February 1995 validation period.
  initial_time: "1995-02-01T01:00:00"
  n_steps: 3



hydra:
  run:
    dir: ${inference.rundir}