# Run historical inference using the ten-year SINGV-trained models.

defaults:
  - dataset/singv_10years
  - model/stormcast
  - sampler/edm_deterministic
  - inference/stormcast
  - _self_

model:
  regression_conditions:
    - state

  diffusion_conditions:
    - state
    - regression

inference:
  outdir: /scratch/users/nus/e1155933/retraining/inference
  experiment_name: singv-diffusion-sampler-test
  run_id: regression-comparison
  seed: 0
  rundir: ${inference.outdir}/${inference.experiment_name}/${inference.run_id}

  regression_checkpoint: /scratch/users/nus/e1155933/retraining/runs/singv-regression-10years/training-100000steps/checkpoints_regression/StormCastUNet.0.100000.mdlus

  diffusion_checkpoint: /scratch/users/nus/e1155933/retraining/runs/singv-diffusion-10years/training-100000steps-bf16-compile/checkpoints_diffusion/EDMPrecond.0.100000.mdlus

  # First input time in the 2005 validation period.
  initial_time: "2005-01-01T01:00:00"

  n_steps: 1

  plot_state_variables:
    - pr
    - tas
    - ta_1000
    - ta_850
    - hus_850
    - zg_500
  plot_var_background: null

  output_state_channels:
    - pr
    - tas
    - ta_1000
    - ta_850
    - hus_850
    - zg_500

  save_vertical_vars: []
  save_vertical_levels: []

  save_horizontal_vars:
    - pr

sampler:
  args:
    num_steps: 18

hydra:
  run:
    dir: ${inference.rundir}
