model_name: 'diffusion'

# Model conditions
regression_conditions: ["state", "background"] 
diffusion_conditions: ["state", "regression"]

# Model hyperparameters
spatial_pos_embed: False 
model_type: "SongUNetPosEmbd"

hyperparameters:
  channel_mult: [1, 2, 2]
  num_blocks: 2
  model_channels: 128
  attn_resolutions: [] 
  checkpoint_level: 0

# Pretrained regression model
regression_weights: "" 