# SINGV dataset configuration for StormCast.

name: singv.SINGVDataset

data_root: ~/scratch/retraining

train_manifest: manifests/week_1995_01_pairs.csv
validation_manifest: manifests/week_1995_01_pairs.csv

normalisation_path: normalisation_stats/week_1995_01_normalisation_stats.npz