# SINGV dataset used for the example 1-month run

name: regression_dataset_adapter.RegressionDatasetAdapter

data_root: ~/scratch/retraining

train_manifest: manifests/training_19950101_19950131.csv
validation_manifest: manifests/validation_19950201_19950207.csv

normalisation_path: normalisation_stats/training_19950101_19950131_normalisation_stats.npz