
outdir: ${dataset.data_root}/inference
experiment_name: singv-inference-1month
run_id: regression-diffusion-comparison
rundir:  ${inference.outdir}/${inference.experiment_name}/${inference.run_id}

regression_checkpoint: ${dataset.data_root}/runs/singv-regression-1month/training-1000steps/checkpoints_regression/StormCastUNet.0.1000.mdlus
diffusion_checkpoint: ${dataset.data_root}/runs/singv-diffusion-1month/training-1000steps/checkpoints_diffusion/EDMPrecond.0.1000.mdlus

# I/O
plot_var_background: null
output_state_channels:
  - tas
  - pr
  - ta_1000
  - ua_1000
  - ta_850
  - zg_500

# you can export inference to NetCDF too but
# this is not done for this example
save_vertical_vars: []
save_vertical_levels: []
save_horizontal_vars: []
